- app/src/main/java/space/taran/arknavigator/mvp/model/repo/AggregatedTagsStorage.kt
> AggregatedTagsStorage fix

- app/build.gradle
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/PreviewsList.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/GalleryView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/PreviewItemView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/PreviewItemViewHolder.kt
- app/src/main/java/space/taran/arknavigator/ui/adapter/PreviewsPager.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/utils/GlideHelper.kt
- app/src/main/res/layout/item_image.xml
> Zoom capability in gallery screen

- app/src/main/java/space/taran/arknavigator/mvp/presenter/FoldersPresenter.kt
- app/src/main/java/space/taran/arknavigator/ui/adapter/FolderPicker.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/FoldersFragment.kt
- Fixed choosing as favorite again crash
- Fixed back click pick button not updating
Requires further testing, since I am not very familiar with the methods in this flow.
> FoldersFragment:

- app/src/main/java/space/taran/arknavigator/mvp/model/dao/Database.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/dao/Resource.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/ResourceMeta.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/ResourcesGridPresenter.kt
- app/src/main/java/space/taran/arknavigator/utils/FileUtils.kt
> #125: Sorting by meta

- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/ui/activity/MainActivity.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/FoldersFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/java/space/taran/arknavigator/utils/FullscreenHelper.kt
- app/src/main/res/layout/activity_main.xml
> #104: Full screen glitch fix

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/FoldersRepo.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/ResourcesIndexRepo.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/tags/TagsStorageRepo.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/FoldersPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/ResourcesPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/dialog/EditTagsDialogPresenter.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/EditTagsDialogFragment.kt
- app/src/main/java/space/taran/arknavigator/utils/LogTags.kt
> #169 Quick tags perfomance

- app/src/main/java/space/taran/arknavigator/di/modules/CiceroneModule.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/PlainResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/FoldersPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/MainPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/ResourcesPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/ResourcesGridPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/folderstree/FoldersTreePresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/tagsselector/TagsSelectorPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/GalleryView.kt
- app/src/main/java/space/taran/arknavigator/navigation/AppNavigator.kt
- app/src/main/java/space/taran/arknavigator/navigation/AppRouter.kt
- app/src/main/java/space/taran/arknavigator/navigation/FragmentForwardAdd.kt
- app/src/main/java/space/taran/arknavigator/ui/activity/MainActivity.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/BackButtonListener.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/FoldersFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/EditTagsDialogFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/view/DepthPageTransformer.kt
> #164: Grid glitch on return

- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
> #184: Deleting resources in row fix

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/PreviewGenerators.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/PreviewsPagerPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/FileItemViewHolder.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/PreviewItemView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/PreviewItemViewHolder.kt
- app/src/main/java/space/taran/arknavigator/ui/adapter/FilesReversibleRVAdapter.kt
- app/src/main/java/space/taran/arknavigator/ui/adapter/PreviewsPager.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/utils/ImageUtils.kt
- app/src/main/res/layout/item_image.xml
Issues covered: #139 #63
Tested with this [photo](https://www.taran.space/photo/20201005_Thessaloniki_4.png)
> #139: Gallery subsampling image view

- app/src/main/java/space/taran/arknavigator/mvp/view/item/FileItemViewHolder.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/PreviewItemViewHolder.kt
- app/src/main/java/space/taran/arknavigator/utils/ImageUtils.kt
> #152: Resource modification is not detected

- app/src/main/java/space/taran/arknavigator/mvp/model/dao/Database.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/dao/ResourceExtra.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/extra/DocumentMetaExtra.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/PlainResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/ResourceMeta.kt
- app/src/main/java/space/taran/arknavigator/ui/extra/DocumentExtraLoader.kt
> #136: Added page count generation to pdf files

- app/build.gradle
- app/src/main/java/space/taran/arknavigator/mvp/model/UserPreferences.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/FoldersPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/dialog/RootsScanDialogPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/FoldersView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/dialog/RootsScanView.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/FoldersFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/RootsScanDialogFragment.kt
- app/src/main/res/layout/dialog_roots_scan.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> #221: Automatic root folders discovery

- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
> #235: Link-to-Web can't be shared

- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/ui/adapter/TagsSelectorAdapter.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/view/DefaultPopup.kt
- app/src/main/res/anim/bottom_fade_scale_in.xml
- app/src/main/res/anim/bottom_fade_scale_out.xml
- app/src/main/res/drawable/bg_rounded_8_stroke.xml
- app/src/main/res/drawable/ic_arrow_right.xml
- app/src/main/res/drawable/ic_delete.xml
- app/src/main/res/layout/popup_gallery_tag_menu.xml
- app/src/main/res/layout/popup_resources_tag_menu.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> #137: Tag context menu

- app/src/main/java/space/taran/arknavigator/di/AppComponent.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/backup/StorageBackup.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preferences/Preferences.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preferences/PreferencesImpl.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/SettingsPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/SettingsView.kt
- app/src/main/java/space/taran/arknavigator/ui/App.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/SettingsFragment.kt
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/values/strings.xml
> #260: Ark files backup

- .github/workflows/build.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/space/taran/arknavigator/di/AppComponent.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preferences/Preferences.kt
- app/src/main/java/space/taran/arknavigator/ui/App.kt
- app/src/main/res/values/strings.xml
> #78: Crashes reporting

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/VideoKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/GeneralPreviewGenerator.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/generator/PdfPreviewGenerator.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/generator/VideoPreviewGenerator.kt
- app/src/main/res/drawable/ic_play.xml
> #33: Preview supports for video files

- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
> 274: Resolved the app crash after deleting last resource in Gallery screen.

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/ResourceKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/VideoKindFactory.kt
> #275: NPE during indexing fix

- app/build.gradle
- app/src/main/java/space/taran/arknavigator/mvp/presenter/ResourcesPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/ResourcesGridPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/ResourcesView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/FileItemView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/FileItemViewHolder.kt
- app/src/main/java/space/taran/arknavigator/ui/activity/MainActivity.kt
- app/src/main/java/space/taran/arknavigator/ui/adapter/ResourcesRVAdapter.kt
- app/src/main/java/space/taran/arknavigator/ui/adapter/TagsSelectorAdapter.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/FoldersFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/SettingsFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/view/DefaultPopup.kt
- app/src/main/java/space/taran/arknavigator/utils/ContextUtils.kt
- app/src/main/java/space/taran/arknavigator/utils/FileUtils.kt
- app/src/main/res/anim/fade_in.xml
- app/src/main/res/anim/fade_out.xml
- app/src/main/res/drawable/bg_rounded_8.xml
- app/src/main/res/drawable/ic_vert_dots.xml
- app/src/main/res/layout/action_bar_resources.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_resources.xml
- app/src/main/res/layout/item_file_grid.xml
- app/src/main/res/layout/popup_gallery_tag_menu.xml
- app/src/main/res/layout/popup_resources_tag_menu.xml
- app/src/main/res/layout/popup_selected_resources_actions.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- build.gradle
> #50: Bulk resources operations

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/AggregatedResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/PlainResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/ResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/ResourcesGridPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/tagsselector/TagsSelectorPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/dialog/EditTagsDialogPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/dialog/EditTagsDialogView.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/EditTagsDialogFragment.kt
- app/src/main/java/space/taran/arknavigator/utils/CoroutineUtils.kt
- app/src/main/res/drawable/bg_rounded_6_top.xml
- app/src/main/res/layout/dialog_edit_tags.xml
- app/src/test/java/space/taran/arknavigator/stub/ResourceIndexStub.kt
> #286: ResourcesIndex isn't thread-safe

- app/src/main/java/space/taran/arknavigator/di/AppComponent.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/FoldersRepo.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/tags/AggregatedTagsStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/tags/PlainTagsStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/tags/TagsStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/ResourcesPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/ResourcesGridPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/dialog/EditTagsDialogPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/ResourcesView.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragmentHelper.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/SettingsFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/ConfirmationDialogFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/EditTagsDialogFragment.kt
- app/src/main/java/space/taran/arknavigator/utils/FileUtils.kt
- app/src/main/res/layout/dialog_edit_tags.xml
- app/src/main/res/layout/dialog_info.xml
- app/src/main/res/layout/popup_selected_resources_actions.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/space/taran/arknavigator/TagSelectorPresenterTest.kt
- app/src/test/java/space/taran/arknavigator/stub/TagsStorageStub.kt
> #292: Improve bulk operations

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/tags/TagsStorageRepo.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/res/layout/fragment_gallery.xml
> #278: Tag chips and edit button visibility and placing

- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/GalleryView.kt
- app/src/main/java/space/taran/arknavigator/ui/extra/DocumentExtraLoader.kt
- app/src/main/java/space/taran/arknavigator/ui/extra/ExtraLoader.kt
- app/src/main/java/space/taran/arknavigator/ui/extra/LinkExtraLoader.kt
- app/src/main/java/space/taran/arknavigator/ui/extra/VideoExtraLoader.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/GalleryFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/DetailsAlertDialog.kt
- app/src/main/res/drawable/bg_dialog_rounded_16dp.xml
- app/src/main/res/drawable/ic_baseline_info.xml
- app/src/main/res/layout/dialog_resource_info.xml
- app/src/main/res/layout/fragment_gallery.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
> #205: Added Info button in gallery

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preferences/Preferences.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preferences/PreferencesImpl.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/SettingsPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/ResourcesGridPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/SettingsView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/FileItemView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/item/FileItemViewHolder.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/SettingsFragment.kt
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/item_file_grid.xml
- app/src/main/res/values/strings.xml
> #300: Short file names

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/LinkKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/generator/LinkPreviewGenerator.kt
- build.gradle
Related to https://github.com/ark-builders/arklib/issues/10
> #287: Use Link-to-Web resource kind from ArkLib

- app/build.gradle
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/LinkKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/generator/LinkPreviewGenerator.kt
#287 should have been solved earlier, but after this PR it must not be re-introduced in the future as well
Thanks @hhio618 :clap:
> Handling Link-to-Web resources using ArkLib

- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/ImageKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/generator/ImagePreviewGenerator.kt
> #306: Extended image types support

- app/src/main/java/space/taran/arknavigator/di/modules/RepoModule.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/ArkFiles.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/AggregatedResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/PlainResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/ResourceMeta.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/ResourcesIndex.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/index/ResourcesIndexRepo.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/ArchiveKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/DocumentKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/ImageKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/LinkKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/PlainTextKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/ResourceKind.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/ResourceKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/kind/VideoKindFactory.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/meta/AggregatedMetadataStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/meta/MetadataStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/meta/MetadataStorageRepo.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/meta/PlainMetadataStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/AggregatedPreviewStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/PlainPreviewStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/preview/PreviewStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/GalleryPresenter.kt
- app/src/main/java/space/taran/arknavigator/ui/extra/ExtraLoader.kt
- app/src/main/java/space/taran/arknavigator/utils/LogTags.kt
> #254: Add metadata storage

- app/.gitignore
- app/build.gradle
- app/src/main/java/space/taran/arknavigator/mvp/model/repo/stats/category/StatsCategoryStorage.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/FoldersPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/FoldersView.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/FoldersFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/ConfirmationDialogFragment.kt
- app/src/main/res/layout/dialog_info.xml
- app/src/main/res/values/strings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> #90: Forgetting roots and favorites

- app/src/main/java/space/taran/arknavigator/ui/adapter/TagsSelectorAdapter.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/res/layout/fragment_resources.xml
- app/src/main/res/layout/item_tag.xml
> Resources screen: tags recyclerview with flexbox

- app/src/main/java/space/taran/arknavigator/mvp/presenter/MainPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/ResourcesPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/presenter/dialog/SortDialogPresenter.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/MainView.kt
- app/src/main/java/space/taran/arknavigator/mvp/view/ResourcesView.kt
- app/src/main/java/space/taran/arknavigator/ui/activity/MainActivity.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/FoldersFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/ResourcesFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/RootsScanDialogFragment.kt
- app/src/main/java/space/taran/arknavigator/ui/fragments/dialog/SortDialogFragment.kt
- app/src/main/res/drawable/order_ascending.xml
- app/src/main/res/drawable/order_descending.xml
- app/src/main/res/layout/action_bar_resources.xml
- app/src/main/res/layout/dialog_roots_scan.xml
- app/src/main/res/layout/dialog_sort.xml
- app/src/main/res/layout/fragment_folders.xml
- app/src/main/res/layout/fragment_resources.xml
- app/src/main/res/values/strings.xml
> UI improve

- .github/workflows/build.yml
- app/build.gradle
- app/src/main/java/space/taran/arknavigator/ui/App.kt
- app/src/main/java/space/taran/arknavigator/ui/activity/MainActivity.kt
[related arklib-android issue](https://github.com/ARK-Builders/arklib-android/issues/1)
> Use debug and release arklib-android

- app/src/main/java/dev/arkbuilders/navigator/presentation/screen/gallery/GalleryFragment.kt
A toast message "Press and Hold to Delete" will be shown when single tapped on Delete Button
> Add toast message (#57)

- app/build.gradle
For #390
Write test execution including test cases with result in log content.
When run `./gradlew testDebugUnitTest` locally:
Test result in GitHub Actions:
> Export test execution result with config

- app/build.gradle
Exclude code coverage analysis
Issue:
> Exclude code coverage analysis

- app/build.gradle
- app/proguard-rules.pro
Reduce apk size
`ark-navigator-arm64-v8a-apk` 34.2 MB -> 28.9 MB
> Enable minify
